name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  http: ^1.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.9
  walletconnect_dart: ^0.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
