name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.0
  http: ^1.2.0
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  web3modal_flutter: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
  
