name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  animations: ^2.0.11
  file_picker: ^8.0.3
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.0
  google_maps_flutter: ^2.6.1
  http: ^1.2.0
  intl: ^0.19.0
  latlong2: ^0.9.1
  open_file: ^3.3.2
  pdf: ^3.10.8
  permission_handler: ^11.3.1
  printing: ^5.12.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  universal_platform: ^1.0.0+1
  url_launcher: ^6.2.5
  web3modal_flutter: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/chat-bot.svg
