# Generated by Django 5.0.2 on 2024-02-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthTokens',
            new_name='AuthToken',
        ),
        migrations.RenameModel(
            old_name='LandTransfers',
            new_name='LandTransfer',
        ),
        migrations.RenameModel(
            old_name='NFTs',
            new_name='NFT',
        ),
        migrations.RenameModel(
            old_name='TaxesFees',
            new_name='TaxesFee',
        ),
    ]
