# Generated by Django 5.0.2 on 2024-02-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_authtokens_authtoken_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='name',
        ),
    ]
