# Generated by Django 5.0.2 on 2024-03-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_wallet_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landtransfer',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='landtransfer',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
