# Generated by Django 5.0.2 on 2024-04-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_landtransfer_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='filer_status',
            field=models.CharField(choices=[('filer', 'Filer'), ('nonfiler', 'Non-Filer')], max_length=50, null=True),
        ),
    ]
