# Generated by Django 5.0.4 on 2024-05-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tehsil',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
